name: Fetch Infisical Token
author: "RikthePixel"
description: "Fetch an Infisical token from Infisical into your Github workflows"
branding:
  icon: "lock"
  color: "yellow"
inputs:
  method:
    description: "The authentication method to use (universal, oidc, aws-iam)"
    required: false
    default: "universal"
  client-id:
    description: "Machine Identity client ID"
    required: false
  client-secret:
    description: "Machine Identity secret key"
    required: false
  identity-id:
    description: "Machine Identity ID"
    required: false
  oidc-audience:
    description: "Custom aud claim for the signed Github ID token"
    required: false
  domain:
    description: "Infisical URL (defaults to https://app.infisical.com )"
    required: false
    default: "https://app.infisical.com"
  extra-headers:
    description: "Extra headers to add to all requests sent to Infisical"
    required: false
    default: ""
runs:
  using: "node20"
  main: "dist/index.cjs"
